package com.dgs.data.domain;
// default package
// Generated 25 Aug, 2016 2:06:53 PM by Hibernate Tools 5.0.0.Alpha3

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MmeAlbumArtistSongMappingId generated by hbm2java
 */
@Embeddable
public class MmeAlbumArtistSongMappingId implements java.io.Serializable {

	private Long albumId;
	private Long artistId;
	private Long songId;

	public MmeAlbumArtistSongMappingId() {
	}

	public MmeAlbumArtistSongMappingId(Long albumId, Long artistId, Long songId) {
		this.albumId = albumId;
		this.artistId = artistId;
		this.songId = songId;
	}

	@Column(name = "Album_ID")
	public Long getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(Long albumId) {
		this.albumId = albumId;
	}

	@Column(name = "Artist_ID")
	public Long getArtistId() {
		return this.artistId;
	}

	public void setArtistId(Long artistId) {
		this.artistId = artistId;
	}

	@Column(name = "Song_ID")
	public Long getSongId() {
		return this.songId;
	}

	public void setSongId(Long songId) {
		this.songId = songId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MmeAlbumArtistSongMappingId))
			return false;
		MmeAlbumArtistSongMappingId castOther = (MmeAlbumArtistSongMappingId) other;

		return ((this.getAlbumId() == castOther.getAlbumId()) || (this.getAlbumId() != null
				&& castOther.getAlbumId() != null && this.getAlbumId().equals(castOther.getAlbumId())))
				&& ((this.getArtistId() == castOther.getArtistId()) || (this.getArtistId() != null
						&& castOther.getArtistId() != null && this.getArtistId().equals(castOther.getArtistId())))
				&& ((this.getSongId() == castOther.getSongId()) || (this.getSongId() != null
						&& castOther.getSongId() != null && this.getSongId().equals(castOther.getSongId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAlbumId() == null ? 0 : this.getAlbumId().hashCode());
		result = 37 * result + (getArtistId() == null ? 0 : this.getArtistId().hashCode());
		result = 37 * result + (getSongId() == null ? 0 : this.getSongId().hashCode());
		return result;
	}

}
