package com.dgs.data.domain;
// default package
// Generated 25 Aug, 2016 2:06:53 PM by Hibernate Tools 5.0.0.Alpha3

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MmePlaylistSongMapping generated by hbm2java
 */
@Entity
@Table(name = "mme_playlist_song_mapping", uniqueConstraints = @UniqueConstraint(columnNames = { "Playlist_ID",
		"Song_ID" }))
public class MmePlaylistSongMapping implements java.io.Serializable {

	private MmePlaylistSongMappingId id;

	public MmePlaylistSongMapping() {
	}

	public MmePlaylistSongMapping(MmePlaylistSongMappingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "playlistId", column = @Column(name = "Playlist_ID", nullable = false)),
			@AttributeOverride(name = "songId", column = @Column(name = "Song_ID", nullable = false)) })
	public MmePlaylistSongMappingId getId() {
		return this.id;
	}

	public void setId(MmePlaylistSongMappingId id) {
		this.id = id;
	}

}
