package com.dgs.data.domain;
// default package
// Generated 25 Aug, 2016 2:06:53 PM by Hibernate Tools 5.0.0.Alpha3

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MmePlaylistSongMappingId generated by hbm2java
 */
@Embeddable
public class MmePlaylistSongMappingId implements java.io.Serializable {

	private long playlistId;
	private long songId;

	public MmePlaylistSongMappingId() {
	}

	public MmePlaylistSongMappingId(long playlistId, long songId) {
		this.playlistId = playlistId;
		this.songId = songId;
	}

	@Column(name = "Playlist_ID", nullable = false)
	public long getPlaylistId() {
		return this.playlistId;
	}

	public void setPlaylistId(long playlistId) {
		this.playlistId = playlistId;
	}

	@Column(name = "Song_ID", nullable = false)
	public long getSongId() {
		return this.songId;
	}

	public void setSongId(long songId) {
		this.songId = songId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MmePlaylistSongMappingId))
			return false;
		MmePlaylistSongMappingId castOther = (MmePlaylistSongMappingId) other;

		return (this.getPlaylistId() == castOther.getPlaylistId()) && (this.getSongId() == castOther.getSongId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPlaylistId();
		result = 37 * result + (int) this.getSongId();
		return result;
	}

}
