package com.dgs.data.domain;
// default package
// Generated 25 Aug, 2016 2:06:53 PM by Hibernate Tools 5.0.0.Alpha3

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MmeSongs generated by hbm2java
 */
@Entity
@Table(name = "mme_songs")
public class MmeSongs implements java.io.Serializable {

	private long songId;
	private String songName;
	private MmeGenre songGenreId;
	private String songFilePath;
	private Long songUploadedBy;
	private Long songUploadModifiedBy;
	private Date songUploadedOn;
	private Date songModifiedOn;

	public MmeSongs() {
	}

	public MmeSongs(long songId, String songName, MmeGenre songGenreId, String songFilePath) {
		this.songId = songId;
		this.songName = songName;
		this.songGenreId = songGenreId;
		this.songFilePath = songFilePath;
	}

	public MmeSongs(long songId, String songName, MmeGenre songGenreId, String songFilePath, Long songUploadedBy,
			Long songUploadModifiedBy, Date songUploadedOn, Date songModifiedOn) {
		this.songId = songId;
		this.songName = songName;
		this.songGenreId = songGenreId;
		this.songFilePath = songFilePath;
		this.songUploadedBy = songUploadedBy;
		this.songUploadModifiedBy = songUploadModifiedBy;
		this.songUploadedOn = songUploadedOn;
		this.songModifiedOn = songModifiedOn;
	}

	@Id

	@Column(name = "Song_ID", unique = true, nullable = false)
	public long getSongId() {
		return this.songId;
	}

	public void setSongId(long songId) {
		this.songId = songId;
	}

	@Column(name = "Song_Name", nullable = false, length = 1000)
	public String getSongName() {
		return this.songName;
	}

	public void setSongName(String songName) {
		this.songName = songName;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Song_Genre_ID", unique = true, nullable = false)
	public MmeGenre getSongGenreId() {
		return this.songGenreId;
	}

	public void setSongGenreId(MmeGenre songGenreId) {
		this.songGenreId = songGenreId;
	}

	@Column(name = "Song_File_Path", nullable = false)
	public String getSongFilePath() {
		return this.songFilePath;
	}

	public void setSongFilePath(String songFilePath) {
		this.songFilePath = songFilePath;
	}

	@Column(name = "Song_Uploaded_By")
	public Long getSongUploadedBy() {
		return this.songUploadedBy;
	}

	public void setSongUploadedBy(Long songUploadedBy) {
		this.songUploadedBy = songUploadedBy;
	}

	@Column(name = "Song_Upload_Modified_By")
	public Long getSongUploadModifiedBy() {
		return this.songUploadModifiedBy;
	}

	public void setSongUploadModifiedBy(Long songUploadModifiedBy) {
		this.songUploadModifiedBy = songUploadModifiedBy;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Song_Uploaded_On", length = 15)
	public Date getSongUploadedOn() {
		return this.songUploadedOn;
	}

	public void setSongUploadedOn(Date songUploadedOn) {
		this.songUploadedOn = songUploadedOn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Song_Modified_On", length = 15)
	public Date getSongModifiedOn() {
		return this.songModifiedOn;
	}

	public void setSongModifiedOn(Date songModifiedOn) {
		this.songModifiedOn = songModifiedOn;
	}

}
