package com.dgs.data.domain;
// default package
// Generated 25 Aug, 2016 2:06:53 PM by Hibernate Tools 5.0.0.Alpha3

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Generated;

/**
 * MmeUser generated by hbm2java
 */
@Entity
@Table(name = "mme_user", uniqueConstraints = @UniqueConstraint(columnNames = "User_Mail_ID"))
public class MmeUser implements java.io.Serializable {

	private long userId;
	private String userMailId;
	private String password;
	private String userRole;
	private String userProfileName;
	private Date userCreatedOn;
	private Date userModifiedOn;

	public MmeUser() {
	}

	public MmeUser(long userId, String userMailId) {
		this.userId = userId;
		this.userMailId = userMailId;
	}

	public MmeUser(long userId, String userMailId, String password, String userRole, String userProfileName,
			Date userCreatedOn, Date userModifiedOn) {
		this.userId = userId;
		this.userMailId = userMailId;
		this.password = password;
		this.userRole = userRole;
		this.userProfileName = userProfileName;
		this.userCreatedOn = userCreatedOn;
		this.userModifiedOn = userModifiedOn;
	}

	@Id
	@GeneratedValue
	@Column(name = "User_ID", unique = true, nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "User_Mail_ID", unique = true, nullable = false)
	public String getUserMailId() {
		return this.userMailId;
	}

	public void setUserMailId(String userMailId) {
		this.userMailId = userMailId;
	}

	@Column(name = "Password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "User_Role", length = 1)
	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	@Column(name = "User_Profile_Name", length = 100)
	public String getUserProfileName() {
		return this.userProfileName;
	}

	public void setUserProfileName(String userProfileName) {
		this.userProfileName = userProfileName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "User_Created_On", length = 29)
	public Date getUserCreatedOn() {
		return this.userCreatedOn;
	}

	public void setUserCreatedOn(Date userCreatedOn) {
		this.userCreatedOn = userCreatedOn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "User_Modified_On", length = 15)
	public Date getUserModifiedOn() {
		return this.userModifiedOn;
	}

	public void setUserModifiedOn(Date userModifiedOn) {
		this.userModifiedOn = userModifiedOn;
	}

}
